#!/usr/bin/env python3
"""catalogue_regles.py — le référentiel v0.5 en entier, pour le rapport de
conformité du livrable : TOUTES les exigences, groupées par catégorie, chacune
sachant d'où vient son verdict.

- `rapport` : liste des ids du rapport machine qui portent le verdict (une règle
  peut en agréger plusieurs : SAN-3 = occurrences poisson + EPA/DHA chiffrés).
- `traitement` (si pas de verdict machine) : conception (garanti par la façon
  dont le menu est composé), processus (garanti par le pipeline lui-même),
  humain (vérificateur humain, ARB-4), info (indicateur sans verdict).

Mise à jour : suivre les avenants de referentiel-repas.md (source d'autorité).
"""

# (titre de catégorie, [règles])
CATEGORIES = [
    ("Arbitrage (ARB)", [
        {"id": "ARB-1", "nom": "Contraintes dures non négociables",
         "exigence": "Une violation dure ⇒ replanification, jamais de dérogation",
         "traitement": "processus",
         "note": "Appliqué par le vérifieur : statut « violations dures » + code de sortie 1 ⇒ replan"},
        {"id": "ARB-2", "nom": "Ordre des contraintes souples",
         "exigence": "santé > bio > CO2e > prix > local (départage)",
         "traitement": "processus",
         "note": "Appliqué aux choix de produits (SKU bio d'abord, France en départage)"},
        {"id": "ARB-3", "nom": "Aucun arbitrage silencieux",
         "exigence": "Toute dérogation affichée avec règle sacrifiée et raison",
         "traitement": "processus",
         "note": "Ce rapport : dérogations, substitutions et non-appariés listés"},
        {"id": "ARB-4", "nom": "Goût en objectif résiduel",
         "exigence": "Maximisé une fois les contraintes satisfaites",
         "traitement": "humain",
         "note": "Relecture et retour utilisateur (gouts.md, SOR-3)"},
    ]),
    ("Paramètres (PAR)", [
        {"id": "PAR-1", "nom": "Convives",
         "exigence": "2 personnes (paramétrable)",
         "traitement": "conception", "note": "Menu composé et chiffré pour 2"},
        {"id": "PAR-2", "nom": "Couverture des repas",
         "exigence": "7 dîners + 2 déj. week-end + 7 petits-déj. + collations",
         "rapport": ["PAR-2"]},
        {"id": "PAR-3", "nom": "Budgets temps",
         "exigence": "Batch ≤ 3 h ; assemblage dîner ≤ 20-25 min actives",
         "traitement": "conception", "note": "Vérifié via TPS-1 et TPS-2 ci-dessous"},
        {"id": "PAR-4", "nom": "Enveloppe budget",
         "exigence": "≈ 500 €/mois → 100-130 €/semaine",
         "traitement": "conception", "note": "Vérifié via PRX-1 ci-dessous"},
        {"id": "PAR-5", "nom": "Équipement déclaré",
         "exigence": "Robot cuiseur, robot pâtissier, four, congélateur, déshydrateur",
         "traitement": "conception", "note": "Toutes les recettes exécutables avec l'équipement déclaré"},
        {"id": "PAR-6", "nom": "Exclusions (nitrites)",
         "exigence": "Charcuterie nitritée (E249-E252) interdite ; aucune allergie",
         "traitement": "conception",
         "note": "Menu sans charcuterie cette semaine ; contrôle OFF par code-barres à l'achat (DAT-1)"},
    ]),
    ("Santé (SAN) — rang 1", [
        {"id": "SAN-1", "nom": "Légumineuses en base",
         "exigence": "Cible ~75 g/j (≥ 6 occ./sem) ; rampe 3-4 occ. les 4 premières semaines",
         "rapport": ["SAN-1"]},
        {"id": "SAN-2", "nom": "Viande rouge & charcuterie",
         "exigence": "≤ ~100 g/sem (EAT-Lancet) ; charcuterie exceptionnelle ; backstop PNNS dur",
         "rapport": ["SAN-2", "SAN-2b"]},
        {"id": "SAN-3", "nom": "Poisson (dont gras)",
         "exigence": "2 repas/sem dont 1 gras ; EPA+DHA ≥ 250 mg/j",
         "rapport": ["SAN-3", "SAN-3 (EPA+DHA)"]},
        {"id": "SAN-4", "nom": "Fruits & légumes",
         "exigence": "≥ 5 portions/j (dur, prorata du périmètre)",
         "rapport": ["SAN-4"]},
        {"id": "SAN-5", "nom": "Féculents complets",
         "exigence": "≥ moitié en complet/semi-complet ; garde-fou bio sur le complet (Cd)",
         "rapport": ["SAN-5"]},
        {"id": "SAN-6", "nom": "Fruits à coque",
         "exigence": "~50 g/j (EAT-Lancet, avenant v0.5) ; cerneaux non salés",
         "rapport": ["SAN-6"]},
        {"id": "SAN-7", "nom": "Sucres libres",
         "exigence": "< 20 g/j (sources ajoutées seulement, pas les fruits)",
         "rapport": ["SAN-7"]},
        {"id": "SAN-8", "nom": "Ultra-transformés (NOVA 4)",
         "exigence": "≤ 1 occurrence/sem ; base = aliments bruts",
         "rapport": ["SAN-8/PAR-6"]},
        {"id": "SAN-9", "nom": "Matières grasses & ALA",
         "exigence": "Olive en priorité + apport ALA quotidien (lin/colza/noix cru)",
         "rapport": ["SAN-9"]},
        {"id": "SAN-10", "nom": "Sel",
         "exigence": "< 5 g/j (OMS) ; pas de resalage systématique",
         "rapport": ["SAN-10"]},
        {"id": "SAN-11", "nom": "Bio par défaut",
         "exigence": "Part bio du panier ≥ 80 % en valeur ; dérogations affichées",
         "rapport": ["SAN-11"]},
        {"id": "SAN-12", "nom": "Charge glycémique basse",
         "exigence": "Légumineuses en base, complets al dente, fruits entiers, raffiné limité",
         "rapport": ["SAN-12"]},
        {"id": "SAN-13", "nom": "Confort digestif (rampe)",
         "exigence": "Montée en fibres ~4 sem ; légumineuses trempées à eau jetée ; peaux retirées",
         "traitement": "conception",
         "note": "Rampe semaine 1 appliquée ; trempages et poivrons rôtis-pelés inscrits aux recettes"},
    ]),
    ("Planète (PLA)", [
        {"id": "PLA-1", "nom": "Empreinte CO₂e",
         "exigence": "≤ 20 kg CO2e/pers/sem (alerte > 30) — Agribalyse",
         "rapport": ["PLA-1"]},
        {"id": "PLA-2", "nom": "Origine (départage)",
         "exigence": "À scores comparables : France > Italie/Espagne > reste",
         "traitement": "conception",
         "note": "Appliqué au choix des SKU — origine affichée ligne à ligne dans le panier"},
        {"id": "PLA-3", "nom": "Saisonnalité France",
         "exigence": "Frais de saison (calendrier du mois) ; hors-saison → conserve/surgelé ; dérog. PLA-3a (UE bio)",
         "rapport": ["PLA-3"]},
        {"id": "PLA-4", "nom": "Fret aérien",
         "exigence": "Aucun produit à fret aérien (dur)",
         "rapport": ["PLA-4"]},
        {"id": "PLA-5", "nom": "Espèces de poisson",
         "exigence": "Non surexploitées ; petits pélagiques et bivalves privilégiés",
         "traitement": "conception",
         "note": "Sardine et maquereau cette semaine — petits pélagiques (lien SAN-3)"},
    ]),
    ("Temps (TPS)", [
        {"id": "TPS-1", "nom": "Batch cooking (durée)",
         "exigence": "Séance ≤ 3 h, ordonnancée (dépendances, four/plaques mutualisés)",
         "rapport": ["TPS-1"]},
        {"id": "TPS-2", "nom": "Assemblage d'un dîner",
         "exigence": "≤ 25 min actives depuis les composants batchés",
         "rapport": ["TPS-2"]},
        {"id": "TPS-3", "nom": "Part issue du batch",
         "exigence": "≥ 70 % des composants des repas de semaine",
         "rapport": ["TPS-3"]},
    ]),
    ("Prix (PRX)", [
        {"id": "PRX-1", "nom": "Prix du panier",
         "exigence": "Dans l'intervalle PAR-4 (100-130 €/sem) ; dépassement affiché avec cause",
         "rapport": ["PRX-1"]},
        {"id": "PRX-2", "nom": "Dérive (4 semaines)",
         "exigence": "Moyenne glissante affichée contre la baseline",
         "traitement": "info",
         "note": "Première semaine mesurée — l'historique se constitue"},
    ]),
    ("Goût (GOU)", [
        {"id": "GOU-1", "nom": "Variété intra-semaine",
         "exigence": "Aucun plat répété ; ≥ 3 bases ; ≥ 3 registres culinaires",
         "rapport": ["GOU-1", "GOU-1b"]},
        {"id": "GOU-2", "nom": "Respect de gouts.md",
         "exigence": "Préférences graduées respectées (seules les exclusions PAR-6 sont dures)",
         "traitement": "conception",
         "note": "Préférence appliquée : cerneaux plutôt que fruits à coque en coquille"},
        {"id": "GOU-3", "nom": "Intérêt gustatif",
         "exigence": "Maximisé à contraintes satisfaites",
         "traitement": "humain", "note": "Vérificateur humain : à toi de goûter (retour via SOR-3)"},
    ]),
    ("Sécurité du batch (SEC)", [
        {"id": "SEC-1", "nom": "Durées de vie des composants",
         "exigence": "Chaque composant batché consommé dans sa DLC (riz 48 h, légumineuses 3 j…)",
         "rapport": ["SEC-1"]},
        {"id": "SEC-2", "nom": "Refroidissement",
         "exigence": "< 2 h avant froid < 4 °C, contenants plats",
         "traitement": "conception",
         "note": "Consigne inscrite au plan de batch (dernière tâche de la séance)"},
    ]),
    ("Sorties (SOR)", [
        {"id": "SOR-1", "nom": "Rapport de conformité",
         "exigence": "Chaque règle → conforme / violée / dérogée, + CO2e, prix, part bio, temps",
         "traitement": "processus", "note": "Ce document"},
        {"id": "SOR-2", "nom": "Provenance des recettes",
         "exigence": "URL source / générée / adaptée, affichée par recette",
         "traitement": "processus", "note": "Affichée sur chaque carte recette"},
        {"id": "SOR-3", "nom": "Livrables éphémères",
         "exigence": "Entrée au corpus à la demande uniquement, avec statut cuisinée/testée",
         "traitement": "processus", "note": "Rien n'est conservé sans demande explicite"},
    ]),
    ("Données des vérifieurs (DAT)", [
        {"id": "DAT-1", "nom": "Open Food Facts",
         "exigence": "NOVA, additifs (nitrites E249-E252), par code-barres",
         "traitement": "processus",
         "note": "Connecté (off.py) — contrôle des emballés à l'achat"},
        {"id": "DAT-2", "nom": "Agribalyse",
         "exigence": "CO2e par aliment, vérifieur de PLA-1",
         "traitement": "processus", "note": "Connecté — Agribalyse 4 (ADEME), couverture affichée dans PLA-1"},
        {"id": "DAT-3", "nom": "Calendrier de saisonnalité",
         "exigence": "France, par mois, vérifieur de PLA-3",
         "traitement": "processus", "note": "Chargé (saisonnalite-fr.md versionné avec le référentiel)"},
    ]),
]

TRAITEMENT_LIBELLE = {
    "processus": ("Processus", "neu"),
    "conception": ("À la conception", "neu"),
    "humain": ("Vérif. humaine", "neu"),
    "info": ("Info", "neu"),
}
